/** Pinned homepage rail: mature (+18) anime. TMDB seasons often share one show id. */

export type AdultAnime = { id: number; type: "tv"; title: string };

export const ADULT_ANIME: AdultAnime[] = [
  { id: 94664, type: "tv", title: "Mushoku Tensei: Jobless Reincarnation" },
  { id: 223564, type: "tv", title: "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You" },
  { id: 123249, type: "tv", title: "My Dress-Up Darling" },
  { id: 325052, type: "tv", title: "KAMUI: He's Behind You" },
  { id: 65844, type: "tv", title: "KONOSUBA - God's blessing on this wonderful world!" },
  { id: 263121, type: "tv", title: "My Dress-Up Darling Season 2" },
  { id: 139287, type: "tv", title: "More than a Married Couple, but Not Lovers" },
  { id: 60808, type: "tv", title: "No Game No Life" },
  { id: 62273, type: "tv", title: "Food Wars! Shokugeki no Soma" },
  { id: 60728, type: "tv", title: "Kill la Kill" },
  { id: 139060, type: "tv", title: "Chained Soldier" },
  { id: 62104, type: "tv", title: "The Seven Deadly Sins" },
  { id: 93019, type: "tv", title: "ORESUKI Are you the only one who loves me?" },
  { id: 216074, type: "tv", title: "2.5 Dimensional Seduction" },
  { id: 261745, type: "tv", title: "The Daily Life of a Middle-Aged Online Shopper in Another World" },
  { id: 56998, type: "tv", title: "High School of the Dead" },
  { id: 72296, type: "tv", title: "My First Girlfriend Is a Gal" },
  { id: 64706, type: "tv", title: "Prison School" },
  { id: 46195, type: "tv", title: "Nisemonogatari" },
  { id: 45950, type: "tv", title: "High School DxD" },
  { id: 69292, type: "tv", title: "Scum's Wish" },
  { id: 236338, type: "tv", title: "Gushing Over Magical Girls" },
  { id: 70883, type: "tv", title: "Love Tyrant" },
  { id: 285818, type: "tv", title: "Mistress Kanan Is Devilishly Easy" },
  { id: 80563, type: "tv", title: "How Not to Summon a Demon Lord" },
  { id: 67154, type: "tv", title: "Chivalry of a Failed Knight" },
  { id: 93149, type: "tv", title: "Plunderer" },
  { id: 83103, type: "tv", title: "Domestic Girlfriend" },
  { id: 234910, type: "tv", title: "Tying the Knot with an Amagami Sister" },
  { id: 98986, type: "tv", title: "Uzaki-chan Wants to Hang Out!" },
  { id: 34805, type: "tv", title: "Sekirei" },
  { id: 46025, type: "tv", title: "Infinite Stratos" },
  { id: 46004, type: "tv", title: "Date A Live" },
  { id: 109805, type: "tv", title: "Anime AzurLane: Slow Ahead!" },
  { id: 273048, type: "tv", title: "I'm Living with an Otaku NEET Kunoichi!?" },
  { id: 273467, type: "tv", title: "The Warrior Princess and the Barbaric King" },
  { id: 63323, type: "tv", title: "SHIMONETA: A Boring World Where the Concept of Dirty Jokes Doesn't Exist" },
];

const ADULT_ANIME_SEARCH_TITLES = [
  "Mushoku Tensei: Jobless Reincarnation Season 3",
  "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You Season 3",
  "Mushoku Tensei: Jobless Reincarnation",
  "Mushoku Tensei: Jobless Reincarnation Cour 2",
  "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2",
  "Mushoku Tensei: Jobless Reincarnation Season 2",
  "My Dress-Up Darling",
  "KAMUI ---He's behind you",
  "KONOSUBA -God's blessing on this wonderful world!",
  "My Dress-Up Darling Season 2",
  "KONOSUBA -God's blessing on this wonderful world! 2",
  "More than a Married Couple, but Not Lovers.",
  "No Game, No Life",
  "Food Wars!",
  "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You Season 2",
  "KONOSUBA -God's blessing on this wonderful world! 3",
  "Kill la Kill",
  "Chained Soldier Season 2",
  "The Seven Deadly Sins",
  "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You",
  "ORESUKI: Are you the only one who loves me?",
  "2.5 Dimensional Seduction",
  "The Daily Life of a Middle-Aged Online Shopper in Another World",
  "High School of the Dead",
  "My First Girlfriend is a Gal",
  "Food Wars! The Second Plate",
  "Prison School",
  "Nisemonogatari",
  "High School DxD",
  "Scum's Wish",
  "Gushing Over Magical Girls",
  "The Seven Deadly Sins: Revival of the Commandments",
  "Love Tyrant",
  "Mistress Kanan is Devilishly Easy",
  "High School DxD NEW",
  "How NOT to Summon a Demon Lord",
  "Chivalry of a Failed Knight",
  "Plunderer",
  "Domestic Girlfriend",
  "Tying the Knot with an Amagami Sister",
  "Uzaki-chan Wants to Hang Out!",
  "Sekirei",
  "Infinite Stratos",
  "Date A Live",
  "Anime AzurLane: Slow Ahead! Season 2",
  "I'm Living With a Otaku NEET Kunoichi?!",
  "The Warrior Princess and the Barbaric King",
  "SHIMONETA: A Boring World Where the Concept of Dirty Jokes Doesn't Exist",
];

export const ADULT_ANIME_KEYWORDS: string[] = [
  "أنمي +18",
  "انمي +18",
  "انمي +18 مترجم",
  "أنميات تصنيف +18",
  "تصنيف عمري +18",
  "انمي للكبار",
  "مشاهدة انمي +18 مترجم اون لاين",
  "18+ anime",
  "ecchi anime subbed",
  ...ADULT_ANIME_SEARCH_TITLES.flatMap((name) => [
    name,
    `مشاهدة ${name}`,
    `انمي ${name} مترجم`,
    `${name} مترجم اون لاين`,
    `${name} +18`,
    `watch ${name}`,
  ]),
];
