/** Pinned homepage rail: mature (+18) anime. TMDB seasons often share one show id. */

export type AdultAnime = { id: number; type: "tv" | "movie"; title: string };

export const ADULT_ANIME: AdultAnime[] = [
  { id: 223564, type: "tv", title: "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You" },
  { id: 80537, type: "tv", title: "HANEBADO!" },
  { id: 290667, type: "tv", title: "An Adventurer's Daily Grind at Age 29" },
  { id: 285818, type: "tv", title: "Mistress Kanan Is Devilishly Easy" },
  { id: 83451, type: "tv", title: "Million Arthur" },
  { id: 76121, type: "tv", title: "DARLING in the FRANXX" },
  { id: 103157, type: "tv", title: "The Hidden Dungeon Only I Can Enter" },
  { id: 357786, type: "movie", title: "Kizumonogatari Part 1: Tekketsu" },
  { id: 362584, type: "movie", title: "Kizumonogatari Part 2: Nekketsu" },
  { id: 362585, type: "movie", title: "Kizumonogatari Part 3: Reiketsu" },
  { id: 1189199, type: "movie", title: "KIZUMONOGATARI -Koyomi Vamp-" },
  { id: 218613, type: "tv", title: "TenPuru" },
  { id: 60868, type: "tv", title: "Walkure Romanze" },
  { id: 101972, type: "tv", title: "Our Last Crusade or the Rise of a New World" },
  { id: 295366, type: "tv", title: "There Was a Cute Girl in the Hero's Party, So I Tried Confessing to Her" },
  { id: 235389, type: "tv", title: "Re:Monster" },
  { id: 997317, type: "movie", title: "Kaguya-sama: Love Is War -The First Kiss That Never Ends-" },
  { id: 209707, type: "tv", title: "The Café Terrace and Its Goddesses" },
  { id: 139060, type: "tv", title: "Chained Soldier" },
  { id: 65332, type: "tv", title: "Amagi Brilliant Park" },
  { id: 326844, type: "tv", title: "Crowned in a Hundred Days" },
  { id: 60733, type: "tv", title: "No-Rin" },
  { id: 195990, type: "tv", title: "Love Flops" },
  { id: 103962, type: "tv", title: "Mother of the Goddess' Dormitory" },
  { id: 235758, type: "tv", title: "Alya Sometimes Hides Her Feelings in Russian" },
  { id: 70883, type: "tv", title: "Love Tyrant" },
  { id: 232926, type: "tv", title: "7th Time Loop: The Villainess Enjoys a Carefree Life Married to Her Worst Enemy!" },
  { id: 261148, type: "tv", title: "The Red Ranger Becomes an Adventurer in Another World" },
  { id: 123528, type: "tv", title: "Skeleton Knight in Another World" },
  { id: 284447, type: "tv", title: "Yowayowa Sensei" },
  { id: 80623, type: "tv", title: "BAKI" },
  { id: 129600, type: "tv", title: "Baki Hanma" },
  { id: 296232, type: "tv", title: "SNOWBALL EARTH" },
  { id: 65851, type: "tv", title: "A Good Librarian Like a Good Shepherd" },
  { id: 121787, type: "tv", title: "takt op.Destiny" },
  { id: 34742, type: "tv", title: "To Love Ru" },
  { id: 382667, type: "movie", title: "To Love-Ru OVA" },
  { id: 200777, type: "tv", title: "The Iceblade Sorcerer Shall Rule the World" },
  { id: 257475, type: "movie", title: "Tamako Love Story" },
  { id: 66926, type: "tv", title: "Valkyrie Drive: Mermaid" },
  { id: 219673, type: "tv", title: "The Kingdoms of Ruin" },
  { id: 213830, type: "tv", title: "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability" },
  { id: 199920, type: "tv", title: "KamiKatsu: Working for God in a Godless World" },
  { id: 296101, type: "tv", title: "GROW UP SHOW -Sunflower Circus-" },
  { id: 299778, type: "tv", title: "Tatsuki Fujimoto 17-26" },
  { id: 46261, type: "tv", title: "Fairy Tail" },
  { id: 248947, type: "tv", title: "FAIRY TAIL 100 YEARS QUEST" },
  { id: 135531, type: "movie", title: "Fairy Tail: Phoenix Priestess" },
  { id: 433422, type: "movie", title: "Fairy Tail: Dragon Cry" },
  { id: 257790, type: "tv", title: "I'm Getting Married to a Girl I Hate in My Class" },
  { id: 314554, type: "tv", title: "From Overshadowed to Overpowered: Second Reincarnation of a Talentless Sage" },
  { id: 270603, type: "tv", title: "The Exiled Heavy Knight Knows How to Game the System" },
  { id: 296286, type: "tv", title: "Smoking Behind the Supermarket with You" },
  { id: 34188, type: "tv", title: "Princess Lover!" },
  { id: 62227, type: "tv", title: "Triage X" },
  { id: 330505, type: "tv", title: "Uncle's Obsession With Cute Things" },
  { id: 65816, type: "tv", title: "Undefeated Bahamut Chronicle" },
  { id: 94664, type: "tv", title: "Mushoku Tensei: Jobless Reincarnation" },
  { id: 123249, type: "tv", title: "My Dress-Up Darling" },
  { id: 325052, type: "tv", title: "KAMUI: He's Behind You" },
  { id: 65844, type: "tv", title: "KONOSUBA - God's blessing on this wonderful world!" },
  { id: 263121, type: "tv", title: "My Dress-Up Darling Season 2" },
  { id: 139287, type: "tv", title: "More than a Married Couple, but Not Lovers" },
  { id: 60808, type: "tv", title: "No Game No Life" },
  { id: 62273, type: "tv", title: "Food Wars! Shokugeki no Soma" },
  { id: 60728, type: "tv", title: "Kill la Kill" },
  { id: 62104, type: "tv", title: "The Seven Deadly Sins" },
  { id: 93019, type: "tv", title: "ORESUKI Are you the only one who loves me?" },
  { id: 216074, type: "tv", title: "2.5 Dimensional Seduction" },
  { id: 261745, type: "tv", title: "The Daily Life of a Middle-Aged Online Shopper in Another World" },
  { id: 56998, type: "tv", title: "High School of the Dead" },
  { id: 72296, type: "tv", title: "My First Girlfriend Is a Gal" },
  { id: 64706, type: "tv", title: "Prison School" },
  { id: 46195, type: "tv", title: "Nisemonogatari" },
  { id: 45950, type: "tv", title: "High School DxD" },
  { id: 69292, type: "tv", title: "Scum's Wish" },
  { id: 236338, type: "tv", title: "Gushing Over Magical Girls" },
  { id: 80563, type: "tv", title: "How Not to Summon a Demon Lord" },
  { id: 67154, type: "tv", title: "Chivalry of a Failed Knight" },
  { id: 93149, type: "tv", title: "Plunderer" },
  { id: 83103, type: "tv", title: "Domestic Girlfriend" },
  { id: 234910, type: "tv", title: "Tying the Knot with an Amagami Sister" },
  { id: 98986, type: "tv", title: "Uzaki-chan Wants to Hang Out!" },
  { id: 34805, type: "tv", title: "Sekirei" },
  { id: 46025, type: "tv", title: "Infinite Stratos" },
  { id: 46004, type: "tv", title: "Date A Live" },
  { id: 109805, type: "tv", title: "Anime AzurLane: Slow Ahead!" },
  { id: 273048, type: "tv", title: "I'm Living with an Otaku NEET Kunoichi!?" },
  { id: 273467, type: "tv", title: "The Warrior Princess and the Barbaric King" },
  { id: 63323, type: "tv", title: "SHIMONETA: A Boring World Where the Concept of Dirty Jokes Doesn't Exist" },
];

const ADULT_ANIME_SEARCH_TITLES = [
  "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You",
  "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You Season 2",
  "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You Season 3",
  "HANEBADO!",
  "An Adventurer's Daily Grind at Age 29",
  "Mistress Kanan is Devilishly Easy",
  "Million Arthur",
  "Han-Gyaku-Sei Million Arthur",
  "DARLING in the FRANXX",
  "The Hidden Dungeon Only I Can Enter",
  "Kizumonogatari Part 1: Tekketsu",
  "Kizumonogatari Part 2: Nekketsu",
  "Kizumonogatari Part 3: Reiketsu",
  "KIZUMONOGATARI -Koyomi Vamp-",
  "TenPuru",
  "Tenpuru: No One Can Live on Loneliness",
  "Walkure Romanze",
  "Our Last Crusade or the Rise of a New World",
  "Our Last Crusade or the Rise of a New World Season 2",
  "There Was a Cute Girl in the Hero's Party, So I Tried Confessing to Her",
  "Re:Monster",
  "Re:Monster Season 2",
  "Kaguya-sama: Love Is War -The First Kiss That Never Ends-",
  "Kaguya-sama: Love Is War – The Stairway to Adulthood",
  "The Café Terrace and Its Goddesses",
  "The Café Terrace and Its Goddesses Season 2",
  "Chained Soldier",
  "Chained Soldier Season 2",
  "Amagi Brilliant Park",
  "Crowned in a Hundred Days",
  "No-Rin",
  "Love Flops",
  "Mother of the Goddess' Dormitory",
  "Alya Sometimes Hides Her Feelings in Russian",
  "Alya Sometimes Hides Her Feelings in Russian Season 2",
  "Love Tyrant",
  "7th Time Loop: The Villainess Enjoys a Carefree Life Married to Her Worst Enemy!",
  "The Red Ranger Becomes an Adventurer in Another World",
  "Skeleton Knight in Another World",
  "Yowayowa Sensei",
  "BAKI",
  "Baki Hanma",
  "SNOWBALL EARTH",
  "A Good Librarian Like a Good Shepherd",
  "takt op.Destiny",
  "To Love Ru",
  "To Love-Ru Darkness",
  "To Love-Ru OVA",
  "The Iceblade Sorcerer Shall Rule the World",
  "Tamako Love Story",
  "Valkyrie Drive: Mermaid",
  "The Kingdoms of Ruin",
  "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability",
  "KamiKatsu: Working for God in a Godless World",
  "GROW UP SHOW -Sunflower Circus-",
  "Tatsuki Fujimoto 17-26",
  "Fairy Tail",
  "FAIRY TAIL 100 YEARS QUEST",
  "Fairy Tail: Phoenix Priestess",
  "Fairy Tail: Dragon Cry",
  "I'm Getting Married to a Girl I Hate in My Class",
  "From Overshadowed to Overpowered: Second Reincarnation of a Talentless Sage",
  "The Exiled Heavy Knight Knows How to Game the System",
  "Smoking Behind the Supermarket with You",
  "Magical Explorer: Reborn as a Side Character in a Fantasy Dating Sim",
  "Princess Lover!",
  "Triage X",
  "Uncle's Obsession With Cute Things",
  "Undefeated Bahamut Chronicle",
  "Mushoku Tensei: Jobless Reincarnation Season 3",
  "Mushoku Tensei: Jobless Reincarnation",
  "Mushoku Tensei: Jobless Reincarnation Cour 2",
  "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2",
  "Mushoku Tensei: Jobless Reincarnation Season 2",
  "My Dress-Up Darling",
  "KAMUI ---He's behind you",
  "KONOSUBA -God's blessing on this wonderful world!",
  "My Dress-Up Darling Season 2",
  "KONOSUBA -God's blessing on this wonderful world! 2",
  "More than a Married Couple, but Not Lovers.",
  "No Game, No Life",
  "Food Wars!",
  "KONOSUBA -God's blessing on this wonderful world! 3",
  "Kill la Kill",
  "The Seven Deadly Sins",
  "ORESUKI: Are you the only one who loves me?",
  "2.5 Dimensional Seduction",
  "The Daily Life of a Middle-Aged Online Shopper in Another World",
  "High School of the Dead",
  "My First Girlfriend is a Gal",
  "Food Wars! The Second Plate",
  "Prison School",
  "Nisemonogatari",
  "High School DxD",
  "Scum's Wish",
  "Gushing Over Magical Girls",
  "The Seven Deadly Sins: Revival of the Commandments",
  "High School DxD NEW",
  "How NOT to Summon a Demon Lord",
  "Chivalry of a Failed Knight",
  "Plunderer",
  "Domestic Girlfriend",
  "Tying the Knot with an Amagami Sister",
  "Uzaki-chan Wants to Hang Out!",
  "Sekirei",
  "Infinite Stratos",
  "Date A Live",
  "Anime AzurLane: Slow Ahead! Season 2",
  "I'm Living With a Otaku NEET Kunoichi?!",
  "The Warrior Princess and the Barbaric King",
  "SHIMONETA: A Boring World Where the Concept of Dirty Jokes Doesn't Exist",
];

export const ADULT_ANIME_KEYWORDS: string[] = [
  "أنمي +18",
  "انمي +18",
  "انمي +18 مترجم",
  "أنميات تصنيف +18",
  "تصنيف عمري +18",
  "انمي للكبار",
  "مشاهدة انمي +18 مترجم اون لاين",
  "18+ anime",
  "ecchi anime subbed",
  ...ADULT_ANIME_SEARCH_TITLES.flatMap((name) => [
    name,
    `مشاهدة ${name}`,
    `انمي ${name} مترجم`,
    `${name} مترجم اون لاين`,
    `${name} +18`,
    `watch ${name}`,
  ]),
];
