/** Pinned foreign / global titles. TMDB seasons/episodes share one show id. */

export type ForeignTitle = { id: number; type: "tv" | "movie"; title: string };

function uniqueForeign(items: ForeignTitle[]): ForeignTitle[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    const key = `${item.type}:${item.id}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export const FOREIGN_TV: ForeignTitle[] = uniqueForeign([
  { id: 323579, type: "tv", title: "GATE24: The Border" },
  { id: 125282, type: "tv", title: "The Cleaning Lady" },
  { id: 1408, type: "tv", title: "House" },
  { id: 63174, type: "tv", title: "Lucifer" },
  { id: 1407, type: "tv", title: "Homeland" },
  { id: 46952, type: "tv", title: "The Blacklist" },
  { id: 1622, type: "tv", title: "Supernatural" },
  { id: 18165, type: "tv", title: "The Vampire Diaries" },
  { id: 37680, type: "tv", title: "Suits" },
  { id: 71712, type: "tv", title: "The Good Doctor" },
  { id: 71789, type: "tv", title: "SEAL Team" },
  { id: 5920, type: "tv", title: "The Mentalist" },
  { id: 66025, type: "tv", title: "Animal Kingdom" },
  { id: 46296, type: "tv", title: "Spartacus" },
  { id: 69478, type: "tv", title: "The Handmaid's Tale" },
  { id: 119051, type: "tv", title: "Wednesday" },
  { id: 71912, type: "tv", title: "The Witcher" },
  { id: 1639, type: "tv", title: "Heroes" },
  { id: 100883, type: "tv", title: "Never Have I Ever" },
  { id: 44217, type: "tv", title: "Vikings" },
  { id: 79744, type: "tv", title: "The Rookie" },
  { id: 74016, type: "tv", title: "The Resident" },
  { id: 1911, type: "tv", title: "Bones" },
  { id: 1402, type: "tv", title: "The Walking Dead" },
  { id: 129552, type: "tv", title: "The Night Agent" },
  { id: 71790, type: "tv", title: "S.W.A.T." },
  { id: 79696, type: "tv", title: "Manifest" },
  { id: 76719, type: "tv", title: "The Rain" },
  { id: 67683, type: "tv", title: "Travelers" },
  { id: 68467, type: "tv", title: "3%" },
  { id: 221817, type: "tv", title: "The Trigger" },
  { id: 67744, type: "tv", title: "Mindhunter" },
  { id: 86423, type: "tv", title: "Locke & Key" },
  { id: 75006, type: "tv", title: "The Umbrella Academy" },
  { id: 39852, type: "tv", title: "The Sinner" },
  { id: 67026, type: "tv", title: "Designated Survivor" },
  { id: 70485, type: "tv", title: "Mr. Mercedes" },
  { id: 111110, type: "tv", title: "One Piece" },
  { id: 19416, type: "tv", title: "Iryu: Team Medical Dragon" },
  { id: 137870, type: "tv", title: "Love Like the Galaxy" },
  { id: 108978, type: "tv", title: "Reacher" },
  { id: 95350, type: "tv", title: "Lanterns" },
  { id: 250307, type: "tv", title: "The Pitt" },
  { id: 66732, type: "tv", title: "Stranger Things" },
  { id: 94997, type: "tv", title: "House of the Dragon" },
  { id: 100088, type: "tv", title: "The Last of Us" },
  { id: 119051, type: "tv", title: "Wednesday" },
  { id: 95396, type: "tv", title: "Severance" },
  { id: 129552, type: "tv", title: "The Night Agent" },
  { id: 91239, type: "tv", title: "Bridgerton" },
  { id: 125988, type: "tv", title: "Silo" },
  { id: 136315, type: "tv", title: "The Bear" },
  { id: 126308, type: "tv", title: "Shōgun" },
  { id: 106379, type: "tv", title: "Fallout" },
  { id: 76479, type: "tv", title: "The Boys" },
  { id: 111803, type: "tv", title: "The White Lotus" },
  { id: 85552, type: "tv", title: "Euphoria" },
  { id: 108978, type: "tv", title: "Reacher" },
  { id: 73586, type: "tv", title: "Yellowstone" },
  { id: 95480, type: "tv", title: "Slow Horses" },
  { id: 82856, type: "tv", title: "The Mandalorian" },
  { id: 84958, type: "tv", title: "Loki" },
  { id: 76331, type: "tv", title: "Succession" },
  { id: 194764, type: "tv", title: "The Penguin" },
  { id: 78191, type: "tv", title: "You" },
  { id: 71912, type: "tv", title: "The Witcher" },
  { id: 71446, type: "tv", title: "Money Heist" },
  { id: 70523, type: "tv", title: "Dark" },
  { id: 96677, type: "tv", title: "Lupin" },
  { id: 76669, type: "tv", title: "Elite" },
  { id: 87739, type: "tv", title: "The Queen's Gambit" },
  { id: 94605, type: "tv", title: "Arcane" },
  { id: 75006, type: "tv", title: "The Umbrella Academy" },
  { id: 81356, type: "tv", title: "Sex Education" },
  { id: 63351, type: "tv", title: "Narcos" },
  { id: 80968, type: "tv", title: "Narcos: Mexico" },
  { id: 90802, type: "tv", title: "The Sandman" },
  { id: 124364, type: "tv", title: "FROM" },
  { id: 79744, type: "tv", title: "The Rookie" },
  { id: 77169, type: "tv", title: "Cobra Kai" },
  { id: 63174, type: "tv", title: "Lucifer" },
  { id: 2288, type: "tv", title: "Prison Break" },
  { id: 4607, type: "tv", title: "Lost" },
  { id: 44217, type: "tv", title: "Vikings" },
  { id: 116135, type: "tv", title: "Vikings: Valhalla" },
  { id: 1402, type: "tv", title: "The Walking Dead" },
  { id: 1399, type: "tv", title: "Game of Thrones" },
  { id: 1396, type: "tv", title: "Breaking Bad" },
  { id: 60059, type: "tv", title: "Better Call Saul" },
  { id: 1668, type: "tv", title: "Friends" },
  { id: 2316, type: "tv", title: "The Office" },
  { id: 1100, type: "tv", title: "How I Met Your Mother" },
  { id: 1416, type: "tv", title: "Grey's Anatomy" },
  { id: 1418, type: "tv", title: "The Big Bang Theory" },
  { id: 1622, type: "tv", title: "Supernatural" },
  { id: 1405, type: "tv", title: "Dexter" },
  { id: 1398, type: "tv", title: "The Sopranos" },
  { id: 1408, type: "tv", title: "House" },
  { id: 19885, type: "tv", title: "Sherlock" },
  { id: 42009, type: "tv", title: "Black Mirror" },
  { id: 60574, type: "tv", title: "Peaky Blinders" },
  { id: 65494, type: "tv", title: "The Crown" },
  { id: 85271, type: "tv", title: "WandaVision" },
  { id: 1412, type: "tv", title: "Arrow" },
  { id: 60735, type: "tv", title: "The Flash" },
  { id: 100757, type: "tv", title: "Outer Banks" },
  { id: 88324, type: "tv", title: "Virgin River" },
  { id: 82596, type: "tv", title: "Emily in Paris" },
  { id: 107113, type: "tv", title: "Only Murders in the Building" },
  { id: 203857, type: "tv", title: "The Diplomat" },
  { id: 124834, type: "tv", title: "Heartstopper" },
  { id: 48866, type: "tv", title: "The 100" },
  { id: 69050, type: "tv", title: "Riverdale" },
  { id: 31917, type: "tv", title: "Pretty Little Liars" },
  { id: 79696, type: "tv", title: "Manifest" },
  { id: 86423, type: "tv", title: "Locke & Key" },
  { id: 103768, type: "tv", title: "Sweet Tooth" },
  { id: 116799, type: "tv", title: "The Lincoln Lawyer" },
  { id: 157744, type: "tv", title: "1923" },
  { id: 46648, type: "tv", title: "True Detective" },
  { id: 90812, type: "tv", title: "Industry" },
  { id: 90669, type: "tv", title: "1899" },
  { id: 154385, type: "tv", title: "Beef" },
]);

export const FOREIGN_MOVIES: ForeignTitle[] = uniqueForeign([
  { id: 1288445, type: "movie", title: "Mutiny" },
  { id: 1084244, type: "movie", title: "Toy Story 5" },
  { id: 436270, type: "movie", title: "Black Adam" },
  { id: 1504358, type: "movie", title: "Don't Say Good Luck" },
  { id: 497814, type: "movie", title: "Breaking In" },
  { id: 913862, type: "movie", title: "Downfall: The Case Against Boeing" },
  { id: 7347, type: "movie", title: "Elite Squad" },
  { id: 1487864, type: "movie", title: "Nando Between Two Worlds" },
  { id: 19995, type: "movie", title: "Avatar" },
  { id: 76600, type: "movie", title: "Avatar: The Way of Water" },
  { id: 597, type: "movie", title: "Titanic" },
  { id: 299534, type: "movie", title: "Avengers: Endgame" },
  { id: 299536, type: "movie", title: "Avengers: Infinity War" },
  { id: 24428, type: "movie", title: "The Avengers" },
  { id: 634649, type: "movie", title: "Spider-Man: No Way Home" },
  { id: 361743, type: "movie", title: "Top Gun: Maverick" },
  { id: 346698, type: "movie", title: "Barbie" },
  { id: 872585, type: "movie", title: "Oppenheimer" },
  { id: 693134, type: "movie", title: "Dune: Part Two" },
  { id: 438631, type: "movie", title: "Dune" },
  { id: 533535, type: "movie", title: "Deadpool & Wolverine" },
  { id: 475557, type: "movie", title: "Joker" },
  { id: 889737, type: "movie", title: "Joker: Folie à Deux" },
  { id: 155, type: "movie", title: "The Dark Knight" },
  { id: 27205, type: "movie", title: "Inception" },
  { id: 157336, type: "movie", title: "Interstellar" },
  { id: 238, type: "movie", title: "The Godfather" },
  { id: 240, type: "movie", title: "The Godfather Part II" },
  { id: 680, type: "movie", title: "Pulp Fiction" },
  { id: 550, type: "movie", title: "Fight Club" },
  { id: 13, type: "movie", title: "Forrest Gump" },
  { id: 278, type: "movie", title: "The Shawshank Redemption" },
  { id: 98, type: "movie", title: "Gladiator" },
  { id: 558449, type: "movie", title: "Gladiator II" },
  { id: 786892, type: "movie", title: "Furiosa: A Mad Max Saga" },
  { id: 402431, type: "movie", title: "Wicked" },
  { id: 1022789, type: "movie", title: "Inside Out 2" },
  { id: 945961, type: "movie", title: "Alien: Romulus" },
  { id: 426063, type: "movie", title: "Nosferatu" },
  { id: 718821, type: "movie", title: "Twisters" },
  { id: 929590, type: "movie", title: "Civil War" },
  { id: 917496, type: "movie", title: "Beetlejuice Beetlejuice" },
  { id: 653346, type: "movie", title: "Kingdom of the Planet of the Apes" },
  { id: 245891, type: "movie", title: "John Wick" },
  { id: 603692, type: "movie", title: "John Wick: Chapter 4" },
  { id: 385687, type: "movie", title: "Fast X" },
  { id: 575264, type: "movie", title: "Mission: Impossible - Dead Reckoning Part One" },
  { id: 575265, type: "movie", title: "Mission: Impossible - The Final Reckoning" },
  { id: 414906, type: "movie", title: "The Batman" },
  { id: 120, type: "movie", title: "The Lord of the Rings: The Fellowship of the Ring" },
  { id: 121, type: "movie", title: "The Lord of the Rings: The Two Towers" },
  { id: 122, type: "movie", title: "The Lord of the Rings: The Return of the King" },
  { id: 671, type: "movie", title: "Harry Potter and the Philosopher's Stone" },
  { id: 603, type: "movie", title: "The Matrix" },
  { id: 569094, type: "movie", title: "Spider-Man: Across the Spider-Verse" },
  { id: 324857, type: "movie", title: "Spider-Man: Into the Spider-Verse" },
  { id: 447365, type: "movie", title: "Guardians of the Galaxy Vol. 3" },
  { id: 109445, type: "movie", title: "Frozen" },
  { id: 354912, type: "movie", title: "Coco" },
  { id: 346364, type: "movie", title: "It" },
  { id: 447332, type: "movie", title: "A Quiet Place" },
  { id: 419430, type: "movie", title: "Get Out" },
  { id: 545611, type: "movie", title: "Everything Everywhere All at Once" },
  { id: 313369, type: "movie", title: "La La Land" },
  { id: 244786, type: "movie", title: "Whiplash" },
  { id: 70160, type: "movie", title: "The Hunger Games" },
  { id: 8966, type: "movie", title: "Twilight" },
  { id: 803796, type: "movie", title: "KPop Demon Hunters" },
  { id: 541671, type: "movie", title: "Ballerina" },
]);

export const FEATURED_FOREIGN_KEYWORDS: string[] = [
  "افلام اجنبية مترجمة",
  "مسلسلات اجنبية مترجمة",
  "هوليوود",
  "أشهر الأفلام الأجنبية",
  "أكثر مسلسلات أجنبية بحثا",
  "hollywood movies",
  "foreign series",
  "watch movies online",
  "Stranger Things",
  "أشياء غريبة",
  "Game of Thrones",
  "صراع العروش",
  "Breaking Bad",
  "The Last of Us",
  "The Boys",
  "Wednesday",
  "ونزداي",
  "Money Heist",
  "la casa de papel",
  "البروفيسور",
  "Friends",
  "فريندز",
  "Prison Break",
  "الهروب من السجن",
  "Avatar",
  "أفاتار",
  "Titanic",
  "تايتنك",
  "Avengers Endgame",
  "Oppenheimer",
  "Dune",
  "Inception",
  "Interstellar",
  "The Dark Knight",
  "The Godfather",
  "الآباء العراب",
];
