/** Pinned Korean dramas and films. TMDB seasons/episodes share one show id. */

export type KoreanTitle = { id: number; type: "tv" | "movie"; title: string };

function uniqueKorean(items: KoreanTitle[]): KoreanTitle[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    const key = `${item.type}:${item.id}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export const KOREAN_TV: KoreanTitle[] = uniqueKorean([
  { id: 296206, type: "tv", title: "Agent Kim Reactivated" },
  { id: 291496, type: "tv", title: "Our Sticky Love" },
  { id: 209110, type: "tv", title: "The Price of Confession" },
  { id: 127529, type: "tv", title: "Bloodhounds" },
  { id: 112833, type: "tv", title: "Juvenile Justice" },
  { id: 99480, type: "tv", title: "The Good Detective" },
  { id: 79070, type: "tv", title: "Partners for Justice" },
  { id: 113622, type: "tv", title: "Sisyphus" },
  { id: 202783, type: "tv", title: "A Killer Paradox" },
  { id: 110356, type: "tv", title: "My Name" },
  { id: 70593, type: "tv", title: "Kingdom" },
  { id: 219246, type: "tv", title: "When Life Gives You Tangerines" },
  { id: 226527, type: "tv", title: "Hierarchy" },
  { id: 212204, type: "tv", title: "Twinkling Watermelon" },
  { id: 215072, type: "tv", title: "A Shop for Killers" },
  { id: 219652, type: "tv", title: "The Frog" },
  { id: 231280, type: "tv", title: "Good Boy" },
  { id: 235355, type: "tv", title: "Resident Playbook" },
  { id: 217553, type: "tv", title: "The Trauma Code: Heroes on Call" },
  { id: 230448, type: "tv", title: "Mr. Plankton" },
  { id: 235577, type: "tv", title: "The Judge from Hell" },
  { id: 241454, type: "tv", title: "Love Next Door" },
  { id: 233349, type: "tv", title: "Cinderella at 2AM" },
  { id: 156484, type: "tv", title: "The 8 Show" },
  { id: 212553, type: "tv", title: "The Bequeathed" },
  { id: 205082, type: "tv", title: "Vigilante" },
  { id: 196474, type: "tv", title: "A Time Called You" },
  { id: 246748, type: "tv", title: "The Tyrant" },
  { id: 226529, type: "tv", title: "Light Shop" },
  { id: 281006, type: "tv", title: "Tastefully Yours" },
  { id: 261980, type: "tv", title: "Our Unwritten Seoul" },
  { id: 258025, type: "tv", title: "Head Over Heels" },
  { id: 233347, type: "tv", title: "Study Group" },
  { id: 232766, type: "tv", title: "Mercy for None" },
  { id: 227191, type: "tv", title: "Nine Puzzles" },
  { id: 211224, type: "tv", title: "The Nice Guy" },
  { id: 233686, type: "tv", title: "Karma" },
  { id: 278904, type: "tv", title: "No Mercy" },
  { id: 93405, type: "tv", title: "Squid Game" },
  { id: 94796, type: "tv", title: "Crash Landing on You" },
  { id: 67915, type: "tv", title: "Guardian: The Lonely and Great God" },
  { id: 65143, type: "tv", title: "Descendants of the Sun" },
  { id: 64010, type: "tv", title: "Reply 1988" },
  { id: 96162, type: "tv", title: "Itaewon Class" },
  { id: 136283, type: "tv", title: "The Glory" },
  { id: 99966, type: "tv", title: "All of Us Are Dead" },
  { id: 70593, type: "tv", title: "Kingdom" },
  { id: 197067, type: "tv", title: "Extraordinary Attorney Woo" },
  { id: 117376, type: "tv", title: "Vincenzo" },
  { id: 154825, type: "tv", title: "Business Proposal" },
  { id: 215720, type: "tv", title: "Queen of Tears" },
  { id: 90447, type: "tv", title: "Hotel Del Luna" },
  { id: 68814, type: "tv", title: "Strong Girl Bong-soon" },
  { id: 68349, type: "tv", title: "Weightlifting Fairy Kim Bok-joo" },
  { id: 70649, type: "tv", title: "While You Were Sleeping" },
  { id: 79434, type: "tv", title: "What's Wrong with Secretary Kim" },
  { id: 112888, type: "tv", title: "True Beauty" },
  { id: 60957, type: "tv", title: "My Love from the Star" },
  { id: 67018, type: "tv", title: "The Legend of the Blue Sea" },
  { id: 48462, type: "tv", title: "The Heirs" },
  { id: 16420, type: "tv", title: "Boys Over Flowers" },
  { id: 37636, type: "tv", title: "Secret Garden" },
  { id: 66433, type: "tv", title: "Scarlet Heart: Ryeo" },
  { id: 75820, type: "tv", title: "Mr. Sunshine" },
  { id: 96102, type: "tv", title: "Hospital Playlist" },
  { id: 74821, type: "tv", title: "Prison Playbook" },
  { id: 64840, type: "tv", title: "Signal" },
  { id: 70626, type: "tv", title: "Stranger" },
  { id: 117378, type: "tv", title: "Mouse" },
  { id: 69087, type: "tv", title: "Voice" },
  { id: 99494, type: "tv", title: "Flower of Evil" },
  { id: 119769, type: "tv", title: "Taxi Driver" },
  { id: 116612, type: "tv", title: "Beyond Evil" },
  { id: 146102, type: "tv", title: "Through the Darkness" },
  { id: 72690, type: "tv", title: "Save Me" },
  { id: 96648, type: "tv", title: "Sweet Home" },
  { id: 110316, type: "tv", title: "Alice in Borderland" },
  { id: 126485, type: "tv", title: "Moving" },
  { id: 218230, type: "tv", title: "Death's Game" },
  { id: 200709, type: "tv", title: "Weak Hero" },
  { id: 127529, type: "tv", title: "Bloodhounds" },
  { id: 158258, type: "tv", title: "Duty After School" },
  { id: 229915, type: "tv", title: "Night Has Come" },
  { id: 135340, type: "tv", title: "Happiness" },
  { id: 75123, type: "tv", title: "A Korean Odyssey" },
  { id: 93846, type: "tv", title: "The King: Eternal Monarch" },
  { id: 116386, type: "tv", title: "Doom at Your Service" },
  { id: 66330, type: "tv", title: "W: Two Worlds Apart" },
  { id: 83634, type: "tv", title: "Memories of the Alhambra" },
  { id: 135157, type: "tv", title: "Alchemy of Souls" },
  { id: 137520, type: "tv", title: "Bulgasal: Immortal Souls" },
  { id: 211747, type: "tv", title: "Island" },
  { id: 113268, type: "tv", title: "The Uncanny Counter" },
  { id: 136369, type: "tv", title: "Tomorrow" },
  { id: 99491, type: "tv", title: "Mystic Pop-up Bar" },
  { id: 121695, type: "tv", title: "Sell Your Haunted House" },
  { id: 106651, type: "tv", title: "Hellbound" },
  { id: 96777, type: "tv", title: "The Silent Sea" },
  { id: 135238, type: "tv", title: "Gyeongseong Creature" },
  { id: 208825, type: "tv", title: "Parasyte: The Grey" },
  { id: 110534, type: "tv", title: "D.P." },
  { id: 202783, type: "tv", title: "A Killer Paradox" },
  { id: 110356, type: "tv", title: "My Name" },
  { id: 210704, type: "tv", title: "The Worst of Evil" },
  { id: 90814, type: "tv", title: "Extracurricular" },
  { id: 112833, type: "tv", title: "Juvenile Justice" },
  { id: 119773, type: "tv", title: "Law School" },
  { id: 71349, type: "tv", title: "Suspicious Partner" },
  { id: 68398, type: "tv", title: "Dr. Romantic" },
  { id: 60956, type: "tv", title: "Doctor Stranger" },
  { id: 73257, type: "tv", title: "Hospital Ship" },
  { id: 152471, type: "tv", title: "Ghost Doctor" },
  { id: 222233, type: "tv", title: "Doctor Slump" },
  { id: 205319, type: "tv", title: "Daily Dose of Sunshine" },
  { id: 96462, type: "tv", title: "It's Okay to Not Be Okay" },
  { id: 62266, type: "tv", title: "Kill Me, Heal Me" },
  { id: 62763, type: "tv", title: "It's Okay, That's Love" },
  { id: 128883, type: "tv", title: "Hometown Cha-Cha-Cha" },
  { id: 135840, type: "tv", title: "Our Blues" },
  { id: 197078, type: "tv", title: "Summer Strike" },
  { id: 219651, type: "tv", title: "Welcome to Samdal-ri" },
  { id: 93097, type: "tv", title: "When the Camellia Blooms" },
  { id: 129888, type: "tv", title: "Twenty Five Twenty One" },
  { id: 99048, type: "tv", title: "Start-Up" },
  { id: 70813, type: "tv", title: "Fight for My Way" },
  { id: 61611, type: "tv", title: "Pinocchio" },
  { id: 54477, type: "tv", title: "I Hear Your Voice" },
  { id: 63767, type: "tv", title: "She Was Pretty" },
  { id: 89641, type: "tv", title: "Love Alarm" },
  { id: 126035, type: "tv", title: "Nevertheless," },
  { id: 218539, type: "tv", title: "My Demon" },
  { id: 198004, type: "tv", title: "King the Land" },
  { id: 216310, type: "tv", title: "Castaway Diva" },
  { id: 221851, type: "tv", title: "Marry My Husband" },
  { id: 230923, type: "tv", title: "Lovely Runner" },
  { id: 154824, type: "tv", title: "See You in My 19th Life" },
  { id: 127231, type: "tv", title: "Shooting Stars" },
  { id: 87553, type: "tv", title: "Her Private Life" },
  { id: 85404, type: "tv", title: "Touch Your Heart" },
  { id: 131028, type: "tv", title: "Thirty-Nine" },
  { id: 96164, type: "tv", title: "The World of the Married" },
  { id: 84327, type: "tv", title: "SKY Castle" },
  { id: 99489, type: "tv", title: "The Penthouse" },
  { id: 91902, type: "tv", title: "Graceful Family" },
  { id: 153496, type: "tv", title: "Reborn Rich" },
  { id: 134675, type: "tv", title: "Little Women" },
  { id: 131305, type: "tv", title: "Celebrity" },
  { id: 156888, type: "tv", title: "Mask Girl" },
  { id: 133775, type: "tv", title: "Remarriage & Desires" },
  { id: 124426, type: "tv", title: "Mine" },
  { id: 138251, type: "tv", title: "Eve" },
  { id: 61148, type: "tv", title: "Empress Ki" },
  { id: 333, type: "tv", title: "Jewel in the Palace" },
  { id: 38852, type: "tv", title: "Dong Yi" },
  { id: 45579, type: "tv", title: "Moon Embracing the Sun" },
  { id: 66496, type: "tv", title: "Hwarang: The Poet Warrior Youth" },
  { id: 132925, type: "tv", title: "The Red Sleeve" },
  { id: 156406, type: "tv", title: "Under the Queen's Umbrella" },
  { id: 129478, type: "tv", title: "The King's Affection" },
  { id: 81821, type: "tv", title: "100 Days My Prince" },
  { id: 90721, type: "tv", title: "Rookie Historian Goo Hae-Ryung" },
  { id: 117896, type: "tv", title: "Lovers of the Red Sky" },
  { id: 206693, type: "tv", title: "My Dearest" },
  { id: 63927, type: "tv", title: "Six Flying Dragons" },
  { id: 88463, type: "tv", title: "Arthdal Chronicles" },
  { id: 41652, type: "tv", title: "Tree with Deep Roots" },
  { id: 71748, type: "tv", title: "Queen For Seven Days" },
  { id: 108284, type: "tv", title: "Tale of the Nine Tailed" },
  { id: 93541, type: "tv", title: "The Tale of Nokdu" },
  { id: 66256, type: "tv", title: "Love in the Moonlight" },
  { id: 70528, type: "tv", title: "Chicago Typewriter" },
  { id: 76662, type: "tv", title: "My Mister" },
  { id: 76092, type: "tv", title: "Mother" },
  { id: 96571, type: "tv", title: "Move to Heaven" },
  { id: 119464, type: "tv", title: "Navillera" },
  { id: 99654, type: "tv", title: "18 Again" },
  { id: 74064, type: "tv", title: "Go Back Couple" },
  { id: 97219, type: "tv", title: "Hi Bye, Mama!" },
  { id: 66272, type: "tv", title: "Uncontrollably Fond" },
  { id: 99112, type: "tv", title: "A Piece of Your Mind" },
  { id: 74074, type: "tv", title: "Because This Is My First Life" },
  { id: 89604, type: "tv", title: "One Spring Night" },
  { id: 78385, type: "tv", title: "Something in the Rain" },
  { id: 113710, type: "tv", title: "Lovestruck in the City" },
  { id: 68945, type: "tv", title: "The Sound of Your Heart" },
  { id: 76557, type: "tv", title: "Welcome to Waikiki" },
  { id: 86830, type: "tv", title: "The Fiery Priest" },
  { id: 201852, type: "tv", title: "One Dollar Lawyer" },
  { id: 135654, type: "tv", title: "Again My Life" },
  { id: 135652, type: "tv", title: "Military Prosecutor Doberman" },
  { id: 155226, type: "tv", title: "Big Mouth" },
  { id: 92983, type: "tv", title: "Vagabond" },
  { id: 67391, type: "tv", title: "The K2" },
  { id: 61670, type: "tv", title: "Healer" },
  { id: 39346, type: "tv", title: "City Hunter" },
  { id: 31505, type: "tv", title: "Iris" },
  { id: 132979, type: "tv", title: "Bad and Crazy" },
  { id: 201019, type: "tv", title: "Tale of the Nine Tailed 1938" },
  { id: 84155, type: "tv", title: "The Sound of Your Heart: Reboot" },
  { id: 57647, type: "tv", title: "Good Doctor" },
]);

export const KOREAN_MOVIES: KoreanTitle[] = uniqueKorean([
  { id: 919207, type: "movie", title: "12.12: The Day" },
  { id: 610251, type: "movie", title: "Harbin" },
  { id: 1075676, type: "movie", title: "Uprising" },
  { id: 1089223, type: "movie", title: "Revolver" },
  { id: 921436, type: "movie", title: "Escape" },
  { id: 965094, type: "movie", title: "Pilot" },
  { id: 1091051, type: "movie", title: "Victory" },
  { id: 936245, type: "movie", title: "Hidden Face" },
  { id: 1002088, type: "movie", title: "Mission: Cross" },
  { id: 793387, type: "movie", title: "Holy Night: Demon Hunters" },
  { id: 1224993, type: "movie", title: "Dark Nuns" },
  { id: 726139, type: "movie", title: "Project Silence" },
  { id: 783110, type: "movie", title: "Smugglers" },
  { id: 901121, type: "movie", title: "Cobweb" },
  { id: 496243, type: "movie", title: "Parasite" },
  { id: 396535, type: "movie", title: "Train to Busan" },
  { id: 670, type: "movie", title: "Oldboy" },
  { id: 11423, type: "movie", title: "Memories of Murder" },
  { id: 290098, type: "movie", title: "The Handmaiden" },
  { id: 49797, type: "movie", title: "I Saw the Devil" },
  { id: 293670, type: "movie", title: "The Wailing" },
  { id: 13855, type: "movie", title: "The Chaser" },
  { id: 51608, type: "movie", title: "The Man from Nowhere" },
  { id: 11344, type: "movie", title: "A Bittersweet Life" },
  { id: 4689, type: "movie", title: "Sympathy for Mr. Vengeance" },
  { id: 4550, type: "movie", title: "Lady Vengeance" },
  { id: 491584, type: "movie", title: "Burning" },
  { id: 705996, type: "movie", title: "Decision to Leave" },
  { id: 30018, type: "movie", title: "Mother" },
  { id: 22536, type: "movie", title: "Thirst" },
  { id: 2440, type: "movie", title: "Joint Security Area" },
  { id: 165213, type: "movie", title: "New World" },
  { id: 479718, type: "movie", title: "The Outlaws" },
  { id: 567646, type: "movie", title: "Extreme Job" },
  { id: 346646, type: "movie", title: "Veteran" },
  { id: 437068, type: "movie", title: "A Taxi Driver" },
  { id: 437103, type: "movie", title: "1987: When the Day Comes" },
  { id: 242452, type: "movie", title: "The Attorney" },
  { id: 133200, type: "movie", title: "Masquerade" },
  { id: 282631, type: "movie", title: "The Admiral: Roaring Currents" },
  { id: 588108, type: "movie", title: "Hansan: Rising Dragon" },
  { id: 660360, type: "movie", title: "Noryang: Deadly Sea" },
  { id: 81481, type: "movie", title: "Silenced" },
  { id: 255709, type: "movie", title: "Hope" },
  { id: 158445, type: "movie", title: "Miracle in Cell No. 7" },
  { id: 313108, type: "movie", title: "Ode to My Father" },
  { id: 11658, type: "movie", title: "Tae Guk Gi: The Brotherhood of War" },
  { id: 436391, type: "movie", title: "The Battleship Island" },
  { id: 79553, type: "movie", title: "The Front Line" },
  { id: 204553, type: "movie", title: "Cold Eyes" },
  { id: 124157, type: "movie", title: "The Thieves" },
  { id: 291549, type: "movie", title: "Assassination" },
  { id: 517991, type: "movie", title: "The Spy Gone North" },
  { id: 435841, type: "movie", title: "Steel Rain" },
  { id: 606400, type: "movie", title: "The Point Men" },
  { id: 727340, type: "movie", title: "Hunt" },
  { id: 434119, type: "movie", title: "Confidential Assignment" },
  { id: 581528, type: "movie", title: "The Gangster, the Cop, the Devil" },
  { id: 453127, type: "movie", title: "Midnight Runners" },
  { id: 437109, type: "movie", title: "The Villainess" },
  { id: 530254, type: "movie", title: "The Witch: Part 1. The Subversion" },
  { id: 615173, type: "movie", title: "The Witch: Part 2. The Other One" },
  { id: 581389, type: "movie", title: "Space Sweepers" },
  { id: 575604, type: "movie", title: "The Call" },
  { id: 614696, type: "movie", title: "#Alive" },
  { id: 581392, type: "movie", title: "Peninsula" },
  { id: 773867, type: "movie", title: "Seoul Vibe" },
  { id: 933131, type: "movie", title: "Badland Hunters" },
  { id: 849869, type: "movie", title: "Kill Boksoon" },
  { id: 518963, type: "movie", title: "Believer" },
  { id: 606523, type: "movie", title: "Night in Paradise" },
  { id: 571785, type: "movie", title: "Time to Hunt" },
  { id: 435366, type: "movie", title: "Fabricated City" },
  { id: 740441, type: "movie", title: "Unlocked" },
  { id: 961268, type: "movie", title: "Ballerina" },
  { id: 800345, type: "movie", title: "Carter" },
  { id: 843794, type: "movie", title: "JUNG_E" },
  { id: 799379, type: "movie", title: "Project Wolf Hunting" },
  { id: 581526, type: "movie", title: "Deliver Us from Evil" },
  { id: 281298, type: "movie", title: "The Divine Move" },
  { id: 813079, type: "movie", title: "Target" },
  { id: 964592, type: "movie", title: "Sleep" },
  { id: 838209, type: "movie", title: "Exhuma" },
  { id: 729854, type: "movie", title: "Concrete Utopia" },
  { id: 626872, type: "movie", title: "Emergency Declaration" },
  { id: 581387, type: "movie", title: "Ashfall" },
  { id: 397567, type: "movie", title: "Along with the Gods: The Two Worlds" },
  { id: 518068, type: "movie", title: "Along with the Gods: The Last 49 Days" },
  { id: 4552, type: "movie", title: "A Tale of Two Sisters" },
  { id: 508642, type: "movie", title: "Gonjiam: Haunted Asylum" },
  { id: 40254, type: "movie", title: "Whispering Corridors" },
  { id: 32242, type: "movie", title: "Phone" },
  { id: 59421, type: "movie", title: "Bedevilled" },
  { id: 745881, type: "movie", title: "The Medium" },
  { id: 628704, type: "movie", title: "Midnight" },
  { id: 79374, type: "movie", title: "Blind" },
  { id: 432836, type: "movie", title: "Memoir of a Murderer" },
  { id: 200085, type: "movie", title: "The Flu" },
  { id: 121491, type: "movie", title: "Deranged" },
  { id: 154030, type: "movie", title: "The Tower" },
  { id: 429450, type: "movie", title: "Pandora" },
  { id: 572164, type: "movie", title: "EXIT" },
  { id: 1255, type: "movie", title: "The Host" },
  { id: 387426, type: "movie", title: "Okja" },
  { id: 110415, type: "movie", title: "Snowpiercer" },
  { id: 18438, type: "movie", title: "Castaway on the Moon" },
  { id: 11178, type: "movie", title: "My Sassy Girl" },
  { id: 42190, type: "movie", title: "The Classic" },
  { id: 15859, type: "movie", title: "A Moment to Remember" },
  { id: 10103, type: "movie", title: "Windstruck" },
  { id: 851644, type: "movie", title: "20th Century Girl" },
  { id: 570503, type: "movie", title: "Tune in for Love" },
  { id: 532444, type: "movie", title: "On Your Wedding Day" },
  { id: 86000, type: "movie", title: "Always" },
  { id: 499028, type: "movie", title: "Be With You" },
  { id: 45098, type: "movie", title: "More Than Blue" },
  { id: 12650, type: "movie", title: "Il Mare" },
  { id: 338729, type: "movie", title: "The Beauty Inside" },
  { id: 448491, type: "movie", title: "Little Forest" },
  { id: 483297, type: "movie", title: "Microhabitat" },
  { id: 615643, type: "movie", title: "Minari" },
  { id: 666277, type: "movie", title: "Past Lives" },
  { id: 547404, type: "movie", title: "House of Hummingbird" },
  { id: 41245, type: "movie", title: "Peppermint Candy" },
  { id: 26955, type: "movie", title: "Oasis" },
  { id: 2015, type: "movie", title: "Secret Sunshine" },
  { id: 47909, type: "movie", title: "Poetry" },
  { id: 113, type: "movie", title: "Spring, Summer, Fall, Winter... and Spring" },
  { id: 1280, type: "movie", title: "3-Iron" },
  { id: 412094, type: "movie", title: "The Net" },
  { id: 354275, type: "movie", title: "Right Now, Wrong Then" },
  { id: 736732, type: "movie", title: "Broker" },
  { id: 45202, type: "movie", title: "The Housemaid" },
  { id: 619803, type: "movie", title: "The Roundup" },
  { id: 955555, type: "movie", title: "The Roundup: No Way Out" },
  { id: 1017163, type: "movie", title: "The Roundup: Punishment" },
  { id: 845222, type: "movie", title: "Kingdom: Ashin of the North" },
  { id: 580626, type: "movie", title: "The Divine Move 2: The Wrathful" },
  { id: 736820, type: "movie", title: "Confidential Assignment 2: International" },
  { id: 995926, type: "movie", title: "I, the Executioner" },
]);

export const FEATURED_KOREAN_KEYWORDS: string[] = [
  "مسلسلات كورية مترجمة",
  "افلام كورية مترجمة",
  "دراما كورية",
  "أشهر المسلسلات الكورية",
  "أكثر مسلسلات كورية بحثا",
  "korean drama",
  "K-drama",
  "korean movies",
  "When Life Gives You Tangerines",
  "عندما تهديك الحياة اليوسفي",
  "Squid Game",
  "لعبة الحبار",
  "Hierarchy",
  "Twinkling Watermelon",
  "A Shop for Killers",
  "The Frog",
  "Good Boy",
  "Resident Playbook",
  "The Trauma Code",
  "Queen of Tears",
  "ملكة الدموع",
  "Lovely Runner",
  "Crash Landing on You",
  "هبوط اضطراري على قلبك",
  "The Glory",
  "المجد",
  "All of Us Are Dead",
  "كلنا أموات",
  "Parasite",
  "الطفيلي",
  "Train to Busan",
  "قطار بوسان",
  "Oldboy",
  "Exhuma",
  "The Roundup",
  "12.12 The Day",
  "Harbin",
];
