/** Pinned Turkish diziler and films. TMDB seasons/episodes share one show id. */

export type TurkishTitle = { id: number; type: "tv" | "movie"; title: string };

function uniqueTurkish(items: TurkishTitle[]): TurkishTitle[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    const key = `${item.type}:${item.id}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export const TURKISH_TV: TurkishTitle[] = uniqueTurkish([
  { id: 274556, type: "tv", title: "Far Away" },
  { id: 245914, type: "tv", title: "Bahar" },
  { id: 259812, type: "tv", title: "Leyla" },
  { id: 256400, type: "tv", title: "Deha" },
  { id: 271014, type: "tv", title: "Siyah Kalp" },
  { id: 240798, type: "tv", title: "Gaddar" },
  { id: 231100, type: "tv", title: "Boundless Love" },
  { id: 241020, type: "tv", title: "Red Roses" },
  { id: 213194, type: "tv", title: "Kızılcık Şerbeti" },
  { id: 210865, type: "tv", title: "Yalı Çapkını" },
  { id: 233314, type: "tv", title: "Another Love" },
  { id: 219446, type: "tv", title: "The Family" },
  { id: 202010, type: "tv", title: "As the Crow Flies" },
  { id: 219826, type: "tv", title: "My Name Is Farah" },
  { id: 251883, type: "tv", title: "Thank You, Next" },
  { id: 228853, type: "tv", title: "The Prince" },
  { id: 214078, type: "tv", title: "Shahmaran" },
  { id: 206180, type: "tv", title: "Another Self" },
  { id: 219064, type: "tv", title: "Who Were We Running From?" },
  { id: 214079, type: "tv", title: "The Tailor" },
  { id: 157219, type: "tv", title: "Midnight at the Pera Palace" },
  { id: 195930, type: "tv", title: "Yakamoz S-245" },
  { id: 136125, type: "tv", title: "The Club" },
  { id: 133490, type: "tv", title: "Family Secrets" },
  { id: 121435, type: "tv", title: "Chrysalis" },
  { id: 109905, type: "tv", title: "The Innocents" },
  { id: 217980, type: "tv", title: "Ömer" },
  { id: 204925, type: "tv", title: "Tozluyaka" },
  { id: 34899, type: "tv", title: "The Magnificent Century" },
  { id: 60930, type: "tv", title: "Magnificent Century: Kösem" },
  { id: 66017, type: "tv", title: "Resurrection: Ertugrul" },
  { id: 95603, type: "tv", title: "Kuruluş Osman" },
  { id: 104877, type: "tv", title: "Love Is in the Air" },
  { id: 65555, type: "tv", title: "Endless Love" },
  { id: 17635, type: "tv", title: "Forbidden Love" },
  { id: 44807, type: "tv", title: "What is Fatmagul's Fault?" },
  { id: 74823, type: "tv", title: "The Pit" },
  { id: 80411, type: "tv", title: "Erkenci Kuş" },
  { id: 87623, type: "tv", title: "Hercai" },
  { id: 79026, type: "tv", title: "The Protector" },
  { id: 112745, type: "tv", title: "Ethos" },
  { id: 100897, type: "tv", title: "Love 101" },
  { id: 52645, type: "tv", title: "Forbidden Fruit" },
  { id: 63549, type: "tv", title: "Love for Rent" },
  { id: 76530, type: "tv", title: "Price Of Passion" },
  { id: 71096, type: "tv", title: "Söz" },
  { id: 136506, type: "tv", title: "The Warrior Princess" },
  { id: 96305, type: "tv", title: "The Ambassador's Daughter" },
  { id: 70798, type: "tv", title: "Bride of Istanbul" },
  { id: 88024, type: "tv", title: "Ruthless City" },
  { id: 80229, type: "tv", title: "Don't Let Go of My Hand" },
  { id: 73506, type: "tv", title: "Full Moon" },
  { id: 69238, type: "tv", title: "Broken Pieces" },
  { id: 60929, type: "tv", title: "Black Money Love" },
  { id: 69459, type: "tv", title: "Wounded Love" },
  { id: 42099, type: "tv", title: "North South" },
  { id: 61867, type: "tv", title: "Medcezir" },
  { id: 64535, type: "tv", title: "Bandits Cannot Rule The World" },
  { id: 17915, type: "tv", title: "One Thousand and One Nights" },
  { id: 4906, type: "tv", title: "Sila" },
  { id: 70926, type: "tv", title: "Gumus" },
  { id: 32519, type: "tv", title: "Ezel" },
  { id: 34587, type: "tv", title: "Valley of the Wolves" },
  { id: 70788, type: "tv", title: "Payitaht: Abdulhamid" },
  { id: 138171, type: "tv", title: "Alparslan: The Great Seljuks" },
  { id: 110655, type: "tv", title: "The Great Seljuks" },
  { id: 96348, type: "tv", title: "The Gift" },
]);

export const TURKISH_MOVIES: TurkishTitle[] = uniqueTurkish([
  { id: 265169, type: "movie", title: "Winter Sleep" },
  { id: 74879, type: "movie", title: "Once Upon a Time in Anatolia" },
  { id: 418472, type: "movie", title: "The Wild Pear Tree" },
  { id: 665733, type: "movie", title: "About Dry Grasses" },
  { id: 8905, type: "movie", title: "Three Monkeys" },
  { id: 18421, type: "movie", title: "Climates" },
  { id: 31026, type: "movie", title: "Distant" },
  { id: 26900, type: "movie", title: "The Bandit" },
  { id: 13393, type: "movie", title: "My Father and My Son" },
  { id: 472454, type: "movie", title: "Ayla: The Daughter of War" },
  { id: 89584, type: "movie", title: "Conquest 1453" },
  { id: 776654, type: "movie", title: "Bergen" },
  { id: 637920, type: "movie", title: "Miracle in Cell No. 7" },
  { id: 171160, type: "movie", title: "The Butterfly's Dream" },
  { id: 528372, type: "movie", title: "Muslum" },
  { id: 57892, type: "movie", title: "Vizontele" },
  { id: 27275, type: "movie", title: "G.O.R.A." },
  { id: 24426, type: "movie", title: "A.R.O.G" },
  { id: 30691, type: "movie", title: "Yahşi Batı" },
  { id: 30634, type: "movie", title: "Magic Carpet Ride" },
  { id: 477313, type: "movie", title: "Between Family" },
  { id: 246524, type: "movie", title: "Wedding Association" },
  { id: 81708, type: "movie", title: "My Grandfather's People" },
  { id: 31060, type: "movie", title: "Recep Ivedik" },
]);

export const FEATURED_TURKISH_KEYWORDS: string[] = [
  "مسلسلات تركية مترجمة",
  "افلام تركية مترجمة",
  "دراما تركية",
  "أشهر المسلسلات التركية",
  "أكثر مسلسلات تركية بحثا",
  "turkish series",
  "turkish movies",
  "türk dizileri",
  "dizi izle",
  "The Magnificent Century",
  "الحريم السلطان",
  "Muhteşem Yüzyıl",
  "Resurrection: Ertugrul",
  "قيامة أرطغرل",
  "Diriliş Ertuğrul",
  "Kuruluş Osman",
  "المؤسس عثمان",
  "Love Is in the Air",
  "الحب منطقي",
  "Sen Çal Kapımı",
  "Endless Love",
  "حب أعمى",
  "Kara Sevda",
  "Forbidden Love",
  "عشق ممنوع",
  "Fatmagul",
  "The Pit",
  "الحفرة",
  "Çukur",
  "Erkenci Kuş",
  "Hercai",
  "Yalı Çapkını",
  "Kızılcık Şerbeti",
  "Kızıl Goncalar",
  "Bahar",
  "Shahmaran",
  "The Club",
  "Family Secrets",
  "Yargı",
  "Ezel",
  "Sila",
  "Gumus",
  "Valley of the Wolves",
  "Winter Sleep",
  "Conquest 1453",
  "Ayla",
  "Bergen",
];
